# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# JVM arguments for the daemon process. 
# Increased to 4GB to improve build performance in projects using Compose and KSP/Kapt.
org.gradle.jvmargs=-Xmx4048m -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError

# Run Gradle in parallel mode to compile multiple modules simultaneously.
org.gradle.parallel=true

# Enable build cache to reuse task outputs from previous builds.
org.gradle.caching=true

# Enable configuration cache to skip the configuration phase when inputs haven't changed.
org.gradle.configuration-cache=true

# Enable Kotlin incremental compilation.
kotlin.incremental=true

# Kapt incremental compilation (if Kapt is used).
# kapt.incremental.apt=true

# AndroidX and Kotlin Code Style
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# SQLDelight 2.2.x AGP 9.0 Compatibility
android.disallowKotlinSourceSets=false

android.newDsl=false

android.r8.proguardAndroidTxt.disallowed=false