name: Android Action Generated APKs

on:
  push:
    branches:
      - trunk
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/trunk' }}

jobs:
  upload_dev_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Create keystore.properties file
        run: echo "${{ secrets.JUST_VERONICA }}" > keystore.properties

      - name: JUST CHILL
        run: |
          mkdir -p key
          echo "${{ secrets.APP_KEY }}" | base64 --decode > key/just_chill_key.p12

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

#      - name: Build Debug (assembleDebug)
#        run: ./gradlew assembleDebug

      - name: Build Release (assembleRelease)
        run: ./gradlew assembleRelease

#      - name: Get Debug APK path
#        id: devDebugPath
#        run: echo "debug=$(find app/build/outputs/apk/debug/*.apk)" >> $GITHUB_OUTPUT

      - name: Get Release APK path
        id: prodDebugPath
        run: echo "release=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

#      - name: upload DEV DEBUG (APP DISTRIBUTION)
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{secrets.FIREBASE_DEV_APP_ID}}
#          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
#          groups: BETSY
#          file: ${{ steps.devDebugPath.outputs.debug }}

      - name: upload RELEASE DEBUG (APP DISTRIBUTION)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_RELEASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Hello
          file: ${{ steps.prodDebugPath.outputs.release }}

#      - name: Upload APK Debug
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ env.date_today }} - APK(s) debug
#          path: app/build/outputs/apk/debug/

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - APK(s) release
          path: app/build/outputs/apk/release/